function data = getConductivityFit_timeVsVt(data,S)
exclude = @(data,idx)excludedata( ...
                conductivityTemperature(data.T(:,idx)),data.S(:,idx), ...
                'range',[100 inf]);

fitdata = @(data,S) cell2mat(arrayfun(@(idx) ...
            coeffvalues(fit(conductivityTemperature( ...
                data.T(:,idx)),data.S(:,idx),'poly1','Exclude',~exclude(data,idx))), ...
                1:numel(S), ...
            'UniformOutput',false)');

getFit  = @(data,S) table(fitdata(data,S), S','VariableNames',{'coeffs','S'});
data    = getFit(data,S);
end

