function maps = colormapclasses(varargin)
cmoceanmaps = {'thermal','balance','haline','delta','solar','curl'...
    'ice','diff','gray','tarn',...
    'oxy','deep','dense','phase',...
    'algae','matter','turbid','topo',...
    'speed','amp','tempo','rain','imfuse'};
builtinmaps = {'parula','jet','hsv','hot','cool','spring',...
    'spring','summer','autumn','winter',...
    'gray','bone','copper','pink','lines',...
    'colorcube','prism','flag','white'};
brewermaps = { 'BrBG','Accent','Blues','PuBuGn',...
    'PiYG','Dark2','BuGn','PuRd','PRGn','Paired','BuPu','Purples',...
  'PuOr','Pastel1','GnBu','RdPu',...
  'RdBu','Pastel2','Greens','Reds',...
  'RdGy','Set1','Greys','YlGn',...
  'RdYlBu','Set2','OrRd','YlGnBu',...
  'RdYlGn','Set3','Oranges','YlOrBr',...
  'Spectral','PuBu','YlOrRd'};

if nargin>0
    map = varargin{1};
    maps = 'builtin';
    if contains(map,cmoceanmaps)
        maps = 'cmocean';
    end
    return
end

maps = cat(2,cmoceanmaps,builtinmaps,brewermaps);

end

