function copyAxes(from,to)
copyobj(from.Children,to)
xlim(to,from.XLim)
ylim(to,from.YLim)
caxis(to,caxis(from))
set(to,'YDir',from.YDir, ...
    'XLabel',from.XLabel,...
    'YLabel',from.YLabel,...
    'TickLabelInterpreter',from.TickLabelInterpreter,...
    'Title',from.Title,...
    'Colormap',from.Colormap);
end

